version: '3.7'

services:
  mainnet-node:
    image: defi/defichain:4.0.0
    restart: always
    ports:
      - '8000:8554'
    volumes:
      - node-data:/data
    command: >
      defid
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcauth=dfx-api:01025f658be49497fce79ac437ccabd5$ca30862f0e10b6be845a3c4d8c0d24961cd6aeef0f021bb8b882ed713704c6c6
      -wallet=dfx-api
      -addresstype=bech32
      -spv=0
