[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[fuzz]
runs = 256

[invariant]
runs = 256
