name: 'nginx-citrea-mainnet'

services:
  nginx:
    image: nginx:1.29.2-perl
    restart: unless-stopped
    networks:
      - shared
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/www:/var/www
    ports:
      - '80:80'

networks:
  shared:
    external: true
    name: citrea-mainnet-network
